name = "echo-web-analytics"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "echo-web-analytics"
database_id = "941985d5-140d-4a72-b1ad-43693129bd0e"

[[kv_namespaces]]
binding = "CACHE"
id = "82e73321ac3b491bac88075d03ac139d"

[vars]
ENVIRONMENT = "production"

[triggers]
crons = ["0 2 * * *"]
